import Head from 'next/head'
import Header from '../components/Header'
import styled from 'styled-components'



const DivIndex = styled.div`
Header{
  width: 90%;
  position: fixed;
  top: 0;
  z-index: 999999999;
  transition: all 0.4s;
  justify-content: space-between;
}
`
export default function Home() {
  return (
    <DivIndex>
      <Head>
        <title>ENO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header  />
      <main>
        {/* Banner */}
        <section>
          {/* Row */}
          {/* Row */}
          {/* Row */}
          {/* Row */}
          {/* Row */}
          {/* Row */}
        </section>
      </main>
      {/* Modal */}
    </DivIndex>
  )
}
